version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: francescoxx/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=francesco
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
    volumes:
      - type: volume
        source: node_db_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  node_db_data: {}
